---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову и категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Веб-сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Обработка и передача платежных данных должны быть корректными
  - Наличие и функционирования системы обратной связи и контактной информации
  - Сайт и его компоненты должны быть доступны в различных регионах и странах
