---
functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Пользователь должен иметь возможность искать товары по ключевому слову и категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Проверка корректности обработки и передачи платежных данных
  - Проверка наличия и функционирования системы обратной связи и контактной информации
  - Проверка доступности сайта и его компонентов в различных регионах и странах
